/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowGestionEmployes (void);
GtkWidget* create_windowAjoutEmploye (void);
GtkWidget* create_windowModifierEmploye (void);
GtkWidget* create_windowSupprimerEmploye (void);
GtkWidget* create_windowListeEmployes (void);
GtkWidget* create_ModifierEmploye (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_windowPointage (void);
GtkWidget* create_windowChamps (void);
GtkWidget* create_dialog5 (void);
GtkWidget* create_dialog6 (void);
GtkWidget* create_gesteq (void);
GtkWidget* create_ajoutereq (void);
GtkWidget* create_Recheq (void);
GtkWidget* create_supeq (void);
GtkWidget* create_listeq (void);
GtkWidget* create_modificationwindow (void);
GtkWidget* create_dialog1has (void);
GtkWidget* create_tache2 (void);
GtkWidget* create_dialog2has (void);
GtkWidget* create_dialog3has (void);
GtkWidget* create_windowHome (void);
