/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowGestionEmployes (void)
{
  GtkWidget *windowGestionEmployes;
  GtkWidget *fixed1;
  GtkWidget *image1;
  GtkWidget *buttonDeconnexionGE;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label3;
  GtkWidget *buttonAcceuilGE;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label1;
  GtkWidget *buttonAjoutEmploye;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label4;
  GtkWidget *buttonSupprimeEmploye;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label6;
  GtkWidget *buttonModifEmploye;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label5;
  GtkWidget *buttonListeEmployes;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label7;
  GtkWidget *buttonPointage;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image32;
  GtkWidget *label52;

  windowGestionEmployes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowGestionEmployes, 500, 500);
  gtk_window_set_title (GTK_WINDOW (windowGestionEmployes), _("Gestion des employ\303\251s"));
  gtk_window_set_resizable (GTK_WINDOW (windowGestionEmployes), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowGestionEmployes), fixed1);

  image1 = create_pixmap (windowGestionEmployes, "final.png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 0, 0);
  gtk_widget_set_size_request (image1, 700, 500);

  buttonDeconnexionGE = gtk_button_new ();
  gtk_widget_show (buttonDeconnexionGE);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonDeconnexionGE, 368, 8);
  gtk_widget_set_size_request (buttonDeconnexionGE, 120, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonDeconnexionGE), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  buttonAcceuilGE = gtk_button_new ();
  gtk_widget_show (buttonAcceuilGE);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAcceuilGE, 272, 8);
  gtk_widget_set_size_request (buttonAcceuilGE, 96, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonAcceuilGE), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  buttonAjoutEmploye = gtk_button_new ();
  gtk_widget_show (buttonAjoutEmploye);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAjoutEmploye, 154, 58);
  gtk_widget_set_size_request (buttonAjoutEmploye, 200, 56);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonAjoutEmploye), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_DND);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_(" Ajouter un employ\303\251"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  buttonSupprimeEmploye = gtk_button_new ();
  gtk_widget_show (buttonSupprimeEmploye);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSupprimeEmploye, 152, 210);
  gtk_widget_set_size_request (buttonSupprimeEmploye, 200, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonSupprimeEmploye), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_DND);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_(" Suprrimer un employ\303\251"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  buttonModifEmploye = gtk_button_new ();
  gtk_widget_show (buttonModifEmploye);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonModifEmploye, 152, 134);
  gtk_widget_set_size_request (buttonModifEmploye, 200, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonModifEmploye), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_DND);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_(" Modifier un employ\303\251"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  buttonListeEmployes = gtk_button_new ();
  gtk_widget_show (buttonListeEmployes);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonListeEmployes, 152, 290);
  gtk_widget_set_size_request (buttonListeEmployes, 200, 56);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonListeEmployes), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_DND);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_(" Liste des employ\303\251s"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox7), label7, FALSE, FALSE, 0);

  buttonPointage = gtk_button_new ();
  gtk_widget_show (buttonPointage);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonPointage, 152, 368);
  gtk_widget_set_size_request (buttonPointage, 200, 56);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (buttonPointage), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image32 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_DND);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox27), image32, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Pointage des employ\303\251s"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox27), label52, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonDeconnexionGE, "clicked",
                    G_CALLBACK (on_buttonDeconnexion_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAcceuilGE, "clicked",
                    G_CALLBACK (on_buttonAcceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAjoutEmploye, "clicked",
                    G_CALLBACK (on_buttonAjoutEmploye_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimeEmploye, "clicked",
                    G_CALLBACK (on_buttonSupprimeEmploye_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifEmploye, "clicked",
                    G_CALLBACK (on_buttonModifEmploye_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonListeEmployes, "clicked",
                    G_CALLBACK (on_buttonListeEmployes_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonPointage, "clicked",
                    G_CALLBACK (on_buttonPointage_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionEmployes, windowGestionEmployes, "windowGestionEmployes");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, buttonDeconnexionGE, "buttonDeconnexionGE");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label3, "label3");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, buttonAcceuilGE, "buttonAcceuilGE");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, buttonAjoutEmploye, "buttonAjoutEmploye");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, buttonSupprimeEmploye, "buttonSupprimeEmploye");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image7, "image7");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label6, "label6");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, buttonModifEmploye, "buttonModifEmploye");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, buttonListeEmployes, "buttonListeEmployes");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label7, "label7");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, buttonPointage, "buttonPointage");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image32, "image32");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label52, "label52");

  gtk_widget_grab_focus (image1);
  return windowGestionEmployes;
}

GtkWidget*
create_windowAjoutEmploye (void)
{
  GtkWidget *windowAjoutEmploye;
  GtkWidget *fixed2;
  GtkWidget *entryNom;
  GtkWidget *entryPrenom;
  GtkWidget *entryCin;
  GtkObject *spinbuttonJours_adj;
  GtkWidget *spinbuttonJours;
  GtkObject *spinbuttonMois_adj;
  GtkWidget *spinbuttonMois;
  GtkObject *spinbuttonAnnees_adj;
  GtkWidget *spinbuttonAnnees;
  GtkWidget *entryGsm;
  GtkWidget *image24;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label15;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label16;
  GtkWidget *buttonAjouter;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label17;
  GtkWidget *buttonDeconnexionAE;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label10;
  GtkWidget *buttonAcceuilAE;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label8;
  GtkWidget *checkbuttonMale;
  GtkWidget *checkbuttonFemelle;

  windowAjoutEmploye = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowAjoutEmploye, 500, 500);
  gtk_window_set_title (GTK_WINDOW (windowAjoutEmploye), _("Ajoute d'employ\303\251s"));
  gtk_window_set_resizable (GTK_WINDOW (windowAjoutEmploye), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowAjoutEmploye), fixed2);

  entryNom = gtk_entry_new ();
  gtk_widget_show (entryNom);
  gtk_fixed_put (GTK_FIXED (fixed2), entryNom, 136, 72);
  gtk_widget_set_size_request (entryNom, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom), 8226);

  entryPrenom = gtk_entry_new ();
  gtk_widget_show (entryPrenom);
  gtk_fixed_put (GTK_FIXED (fixed2), entryPrenom, 136, 128);
  gtk_widget_set_size_request (entryPrenom, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrenom), 8226);

  entryCin = gtk_entry_new ();
  gtk_widget_show (entryCin);
  gtk_fixed_put (GTK_FIXED (fixed2), entryCin, 136, 296);
  gtk_widget_set_size_request (entryCin, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCin), 8226);

  spinbuttonJours_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonJours = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJours_adj), 1, 0);
  gtk_widget_show (spinbuttonJours);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonJours, 136, 192);
  gtk_widget_set_size_request (spinbuttonJours, 80, 24);

  spinbuttonMois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonMois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMois_adj), 1, 0);
  gtk_widget_show (spinbuttonMois);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonMois, 224, 192);
  gtk_widget_set_size_request (spinbuttonMois, 80, 24);

  spinbuttonAnnees_adj = gtk_adjustment_new (1, 1900, 2021, 1, 10, 10);
  spinbuttonAnnees = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnnees_adj), 1, 0);
  gtk_widget_show (spinbuttonAnnees);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonAnnees, 312, 192);
  gtk_widget_set_size_request (spinbuttonAnnees, 88, 24);

  entryGsm = gtk_entry_new ();
  gtk_widget_show (entryGsm);
  gtk_fixed_put (GTK_FIXED (fixed2), entryGsm, 136, 360);
  gtk_widget_set_size_request (entryGsm, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryGsm), 8226);

  image24 = create_pixmap (windowAjoutEmploye, "10.JPG");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed2), image24, 0, 0);
  gtk_widget_set_size_request (image24, 600, 530);

  label11 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 0, 72);
  gtk_widget_set_size_request (label11, 88, 32);

  label12 = gtk_label_new (_("Prenom : "));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 0, 128);
  gtk_widget_set_size_request (label12, 88, 32);

  label15 = gtk_label_new (_("N\303\251(e) le : "));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 0, 184);
  gtk_widget_set_size_request (label15, 96, 40);

  label13 = gtk_label_new (_("Sexe : "));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 8, 240);
  gtk_widget_set_size_request (label13, 88, 40);

  label14 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 0, 296);
  gtk_widget_set_size_request (label14, 96, 32);

  label16 = gtk_label_new (_("GSM :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 0, 360);
  gtk_widget_set_size_request (label16, 96, 32);

  buttonAjouter = gtk_button_new ();
  gtk_widget_show (buttonAjouter);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAjouter, 200, 424);
  gtk_widget_set_size_request (buttonAjouter, 136, 48);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonAjouter), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_DND);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox11), label17, FALSE, FALSE, 0);

  buttonDeconnexionAE = gtk_button_new ();
  gtk_widget_show (buttonDeconnexionAE);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonDeconnexionAE, 368, 8);
  gtk_widget_set_size_request (buttonDeconnexionAE, 120, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonDeconnexionAE), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox10), label10, FALSE, FALSE, 0);

  buttonAcceuilAE = gtk_button_new ();
  gtk_widget_show (buttonAcceuilAE);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAcceuilAE, 272, 8);
  gtk_widget_set_size_request (buttonAcceuilAE, 96, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonAcceuilAE), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox8), label8, FALSE, FALSE, 0);

  checkbuttonMale = gtk_check_button_new_with_mnemonic (_("Male"));
  gtk_widget_show (checkbuttonMale);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbuttonMale, 136, 248);
  gtk_widget_set_size_request (checkbuttonMale, 118, 24);

  checkbuttonFemelle = gtk_check_button_new_with_mnemonic (_("Femelle"));
  gtk_widget_show (checkbuttonFemelle);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbuttonFemelle, 256, 248);
  gtk_widget_set_size_request (checkbuttonFemelle, 118, 24);

  g_signal_connect ((gpointer) buttonAjouter, "clicked",
                    G_CALLBACK (on_buttonAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonDeconnexionAE, "clicked",
                    G_CALLBACK (on_buttonDeconnexion_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAcceuilAE, "clicked",
                    G_CALLBACK (on_buttonAcceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonMale, "toggled",
                    G_CALLBACK (on_checkbuttonMale_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonFemelle, "toggled",
                    G_CALLBACK (on_checkbuttonFemelle_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAjoutEmploye, windowAjoutEmploye, "windowAjoutEmploye");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, entryNom, "entryNom");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, entryPrenom, "entryPrenom");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, entryCin, "entryCin");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, spinbuttonJours, "spinbuttonJours");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, spinbuttonMois, "spinbuttonMois");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, spinbuttonAnnees, "spinbuttonAnnees");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, entryGsm, "entryGsm");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, image24, "image24");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label11, "label11");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label12, "label12");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label15, "label15");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label13, "label13");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label14, "label14");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label16, "label16");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, buttonAjouter, "buttonAjouter");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label17, "label17");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, buttonDeconnexionAE, "buttonDeconnexionAE");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, image11, "image11");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label10, "label10");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, buttonAcceuilAE, "buttonAcceuilAE");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label8, "label8");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, checkbuttonMale, "checkbuttonMale");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, checkbuttonFemelle, "checkbuttonFemelle");

  return windowAjoutEmploye;
}

GtkWidget*
create_windowModifierEmploye (void)
{
  GtkWidget *windowModifierEmploye;
  GtkWidget *fixed3;
  GtkWidget *entryUsername;
  GtkWidget *image25;
  GtkWidget *buttonAcceuilME;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image21;
  GtkWidget *label29;
  GtkWidget *buttonDeconnexionME;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image23;
  GtkWidget *label31;
  GtkWidget *treeview1;
  GtkWidget *buttonRechercher;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label19;
  GtkWidget *buttonModif;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image28;
  GtkWidget *label34;
  GtkWidget *label18;

  windowModifierEmploye = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowModifierEmploye, 630, 305);
  gtk_window_set_title (GTK_WINDOW (windowModifierEmploye), _("Modifier un employ\303\251"));
  gtk_window_set_resizable (GTK_WINDOW (windowModifierEmploye), FALSE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowModifierEmploye), fixed3);

  entryUsername = gtk_entry_new ();
  gtk_widget_show (entryUsername);
  gtk_fixed_put (GTK_FIXED (fixed3), entryUsername, 216, 96);
  gtk_widget_set_size_request (entryUsername, 240, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUsername), 8226);

  image25 = create_pixmap (windowModifierEmploye, "60.jpg");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed3), image25, 0, 0);
  gtk_widget_set_size_request (image25, 700, 300);
  gtk_misc_set_alignment (GTK_MISC (image25), 1, 0.42);

  buttonAcceuilME = gtk_button_new ();
  gtk_widget_show (buttonAcceuilME);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonAcceuilME, 392, 8);
  gtk_widget_set_size_request (buttonAcceuilME, 96, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (buttonAcceuilME), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image21 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox20), image21, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox20), label29, FALSE, FALSE, 0);

  buttonDeconnexionME = gtk_button_new ();
  gtk_widget_show (buttonDeconnexionME);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonDeconnexionME, 488, 8);
  gtk_widget_set_size_request (buttonDeconnexionME, 120, 32);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (buttonDeconnexionME), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image23 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox22), image23, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox22), label31, FALSE, FALSE, 0);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 16, 240);
  gtk_widget_set_size_request (treeview1, 600, 55);

  buttonRechercher = gtk_button_new ();
  gtk_widget_show (buttonRechercher);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonRechercher, 176, 160);
  gtk_widget_set_size_request (buttonRechercher, 130, 40);
  gtk_container_set_border_width (GTK_CONTAINER (buttonRechercher), 3);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonRechercher), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_SMALL_TOOLBAR);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox12), label19, FALSE, FALSE, 0);

  buttonModif = gtk_button_new ();
  gtk_widget_show (buttonModif);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonModif, 320, 160);
  gtk_widget_set_size_request (buttonModif, 130, 40);
  gtk_container_set_border_width (GTK_CONTAINER (buttonModif), 3);
  gtk_widget_set_sensitive (buttonModif, FALSE);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (buttonModif), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image28 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_SMALL_TOOLBAR);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox24), image28, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox24), label34, FALSE, FALSE, 0);

  label18 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 80, 88);
  gtk_widget_set_size_request (label18, 144, 48);

  g_signal_connect ((gpointer) buttonAcceuilME, "clicked",
                    G_CALLBACK (on_buttonAcceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonDeconnexionME, "clicked",
                    G_CALLBACK (on_buttonDeconnexion_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRechercher, "clicked",
                    G_CALLBACK (on_buttonRechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModif, "clicked",
                    G_CALLBACK (on_buttonModif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowModifierEmploye, windowModifierEmploye, "windowModifierEmploye");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, entryUsername, "entryUsername");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, image25, "image25");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, buttonAcceuilME, "buttonAcceuilME");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, image21, "image21");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, label29, "label29");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, buttonDeconnexionME, "buttonDeconnexionME");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, image23, "image23");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, label31, "label31");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, buttonRechercher, "buttonRechercher");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, image13, "image13");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, label19, "label19");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, buttonModif, "buttonModif");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, image28, "image28");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, label34, "label34");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, label18, "label18");

  return windowModifierEmploye;
}

GtkWidget*
create_windowSupprimerEmploye (void)
{
  GtkWidget *windowSupprimerEmploye;
  GtkWidget *fixed4;
  GtkWidget *entryUsername;
  GtkWidget *image26;
  GtkWidget *label20;
  GtkWidget *treeview2;
  GtkWidget *buttonDeconnexionSE;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image20;
  GtkWidget *label28;
  GtkWidget *buttonAcceuilSE;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image19;
  GtkWidget *label27;
  GtkWidget *RechercherSupp;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image31;
  GtkWidget *label50;
  GtkWidget *buttonSupprimer;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label21;

  windowSupprimerEmploye = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowSupprimerEmploye, 630, 305);
  gtk_window_set_title (GTK_WINDOW (windowSupprimerEmploye), _("Supprimer un employ\303\251"));
  gtk_window_set_resizable (GTK_WINDOW (windowSupprimerEmploye), FALSE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (windowSupprimerEmploye), fixed4);

  entryUsername = gtk_entry_new ();
  gtk_widget_show (entryUsername);
  gtk_fixed_put (GTK_FIXED (fixed4), entryUsername, 216, 96);
  gtk_widget_set_size_request (entryUsername, 240, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUsername), 8226);

  image26 = create_pixmap (windowSupprimerEmploye, "40.JPG");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed4), image26, 0, 0);
  gtk_widget_set_size_request (image26, 400, 200);

  label20 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 80, 88);
  gtk_widget_set_size_request (label20, 144, 48);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview2, 16, 240);
  gtk_widget_set_size_request (treeview2, 600, 55);

  buttonDeconnexionSE = gtk_button_new ();
  gtk_widget_show (buttonDeconnexionSE);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonDeconnexionSE, 488, 8);
  gtk_widget_set_size_request (buttonDeconnexionSE, 120, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonDeconnexionSE), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image20 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox19), image20, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox19), label28, FALSE, FALSE, 0);

  buttonAcceuilSE = gtk_button_new ();
  gtk_widget_show (buttonAcceuilSE);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonAcceuilSE, 384, 8);
  gtk_widget_set_size_request (buttonAcceuilSE, 96, 32);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonAcceuilSE), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image19 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox18), image19, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox18), label27, FALSE, FALSE, 0);

  RechercherSupp = gtk_button_new ();
  gtk_widget_show (RechercherSupp);
  gtk_fixed_put (GTK_FIXED (fixed4), RechercherSupp, 152, 144);
  gtk_widget_set_size_request (RechercherSupp, 130, 40);
  gtk_container_set_border_width (GTK_CONTAINER (RechercherSupp), 3);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (RechercherSupp), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image31 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox26), image31, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox26), label50, FALSE, FALSE, 0);

  buttonSupprimer = gtk_button_new ();
  gtk_widget_show (buttonSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonSupprimer, 304, 144);
  gtk_widget_set_size_request (buttonSupprimer, 130, 40);
  gtk_container_set_border_width (GTK_CONTAINER (buttonSupprimer), 3);
  gtk_widget_set_sensitive (buttonSupprimer, FALSE);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonSupprimer), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox13), label21, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonDeconnexionSE, "clicked",
                    G_CALLBACK (on_buttonDeconnexion_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAcceuilSE, "clicked",
                    G_CALLBACK (on_buttonAcceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) RechercherSupp, "clicked",
                    G_CALLBACK (on_RechercherSupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimer, "clicked",
                    G_CALLBACK (on_buttonSupprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowSupprimerEmploye, windowSupprimerEmploye, "windowSupprimerEmploye");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, entryUsername, "entryUsername");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, image26, "image26");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, label20, "label20");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, buttonDeconnexionSE, "buttonDeconnexionSE");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, image20, "image20");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, label28, "label28");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, buttonAcceuilSE, "buttonAcceuilSE");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, image19, "image19");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, label27, "label27");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, RechercherSupp, "RechercherSupp");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, image31, "image31");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, label50, "label50");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, buttonSupprimer, "buttonSupprimer");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, image14, "image14");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, label21, "label21");

  return windowSupprimerEmploye;
}

GtkWidget*
create_windowListeEmployes (void)
{
  GtkWidget *windowListeEmployes;
  GtkWidget *fixed5;
  GtkWidget *buttonDeconnexionLE;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label23;
  GtkWidget *buttonAcceuilLE;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image16;
  GtkWidget *label24;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview;
  GtkWidget *buttonRefresh;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image27;
  GtkWidget *label33;

  windowListeEmployes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowListeEmployes, 700, 500);
  gtk_window_set_title (GTK_WINDOW (windowListeEmployes), _("Consulter la liste des employ\303\251s"));
  gtk_window_set_resizable (GTK_WINDOW (windowListeEmployes), FALSE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (windowListeEmployes), fixed5);

  buttonDeconnexionLE = gtk_button_new ();
  gtk_widget_show (buttonDeconnexionLE);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonDeconnexionLE, 368, 8);
  gtk_widget_set_size_request (buttonDeconnexionLE, 120, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonDeconnexionLE), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox14), label23, FALSE, FALSE, 0);

  buttonAcceuilLE = gtk_button_new ();
  gtk_widget_show (buttonAcceuilLE);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonAcceuilLE, 272, 8);
  gtk_widget_set_size_request (buttonAcceuilLE, 96, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonAcceuilLE), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image16 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox15), image16, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox15), label24, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow1, 16, 56);
  gtk_widget_set_size_request (scrolledwindow1, 488, 328);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview);

  buttonRefresh = gtk_button_new ();
  gtk_widget_show (buttonRefresh);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonRefresh, 544, 192);
  gtk_widget_set_size_request (buttonRefresh, 112, 48);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (buttonRefresh), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image27 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox23), image27, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Refresh"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox23), label33, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonDeconnexionLE, "clicked",
                    G_CALLBACK (on_buttonDeconnexion_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAcceuilLE, "clicked",
                    G_CALLBACK (on_buttonAcceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRefresh, "clicked",
                    G_CALLBACK (on_buttonRefresh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowListeEmployes, windowListeEmployes, "windowListeEmployes");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, buttonDeconnexionLE, "buttonDeconnexionLE");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, image15, "image15");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, label23, "label23");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, buttonAcceuilLE, "buttonAcceuilLE");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, image16, "image16");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, label24, "label24");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, buttonRefresh, "buttonRefresh");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, image27, "image27");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, label33, "label33");

  return windowListeEmployes;
}

GtkWidget*
create_windowChamps (void)
{
  GtkWidget *windowChamps;
  GtkWidget *fixed6;
  GtkWidget *label32;

  windowChamps = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowChamps), _("Erreur"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (windowChamps), fixed6);

  label32 = gtk_label_new (_("Veuillez remplir tous les champs !"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed6), label32, 40, 32);
  gtk_widget_set_size_request (label32, 272, 80);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowChamps, windowChamps, "windowChamps");
  GLADE_HOOKUP_OBJECT (windowChamps, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowChamps, label32, "label32");

  return windowChamps;
}

GtkWidget*
create_ModifierEmploye (void)
{
  GtkWidget *ModifierEmploye;
  GtkWidget *fixed7;
  GtkWidget *entryModifierNom;
  GtkWidget *entryModifierCin;
  GtkWidget *entryModifierGsm;
  GtkObject *spinbuttonModifierJour_adj;
  GtkWidget *spinbuttonModifierJour;
  GtkObject *spinbuttonModifierMois_adj;
  GtkWidget *spinbuttonModifierMois;
  GtkObject *spinbuttonModifierAnnee_adj;
  GtkWidget *spinbuttonModifierAnnee;
  GtkWidget *image30;
  GtkWidget *label36;
  GtkWidget *label41;
  GtkWidget *label47;
  GtkWidget *label46;
  GtkWidget *label42;
  GtkWidget *entryModifierPrenom;
  GtkWidget *buttonConfirmerModif;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image29;
  GtkWidget *label35;
  GtkWidget *checkbuttonModifierMale;
  GtkWidget *checkbuttonModifierFemelle;
  GtkWidget *label43;

  ModifierEmploye = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ModifierEmploye, 320, 291);
  gtk_window_set_title (GTK_WINDOW (ModifierEmploye), _("Modification"));
  gtk_window_set_resizable (GTK_WINDOW (ModifierEmploye), FALSE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (ModifierEmploye), fixed7);

  entryModifierNom = gtk_entry_new ();
  gtk_widget_show (entryModifierNom);
  gtk_fixed_put (GTK_FIXED (fixed7), entryModifierNom, 128, 8);
  gtk_widget_set_size_request (entryModifierNom, 176, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryModifierNom), 8226);

  entryModifierCin = gtk_entry_new ();
  gtk_widget_show (entryModifierCin);
  gtk_fixed_put (GTK_FIXED (fixed7), entryModifierCin, 128, 152);
  gtk_widget_set_size_request (entryModifierCin, 176, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryModifierCin), 8226);

  entryModifierGsm = gtk_entry_new ();
  gtk_widget_show (entryModifierGsm);
  gtk_fixed_put (GTK_FIXED (fixed7), entryModifierGsm, 128, 184);
  gtk_widget_set_size_request (entryModifierGsm, 176, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryModifierGsm), 8226);

  spinbuttonModifierJour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonModifierJour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonModifierJour_adj), 1, 0);
  gtk_widget_show (spinbuttonModifierJour);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonModifierJour, 120, 80);
  gtk_widget_set_size_request (spinbuttonModifierJour, 60, 27);

  spinbuttonModifierMois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonModifierMois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonModifierMois_adj), 1, 0);
  gtk_widget_show (spinbuttonModifierMois);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonModifierMois, 184, 80);
  gtk_widget_set_size_request (spinbuttonModifierMois, 60, 27);

  spinbuttonModifierAnnee_adj = gtk_adjustment_new (1, 1900, 2021, 1, 10, 10);
  spinbuttonModifierAnnee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonModifierAnnee_adj), 1, 0);
  gtk_widget_show (spinbuttonModifierAnnee);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonModifierAnnee, 248, 80);
  gtk_widget_set_size_request (spinbuttonModifierAnnee, 60, 27);

  image30 = create_pixmap (ModifierEmploye, "modif.jpg");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed7), image30, 0, 0);
  gtk_widget_set_size_request (image30, 400, 340);
  gtk_misc_set_alignment (GTK_MISC (image30), 0.1, 0.45);

  label36 = gtk_label_new (_("<span foreground =\"#2020\"><b>Nom\t :</b></span>"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed7), label36, 0, 8);
  gtk_widget_set_size_request (label36, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  label41 = gtk_label_new (_("<span foreground =\"#2020\"><b>Prenom \t:</b></span>"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed7), label41, 0, 40);
  gtk_widget_set_size_request (label41, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  label47 = gtk_label_new (_("<span foreground =\"#2020\"><b>Naissance :</b></span>"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed7), label47, 0, 80);
  gtk_widget_set_size_request (label47, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  label46 = gtk_label_new (_("<span foreground =\"#2020\"><b>Sexe \t:</b></span>"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed7), label46, 0, 112);
  gtk_widget_set_size_request (label46, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  label42 = gtk_label_new (_("<span foreground =\"#2020\"><b>CIN\t\t: </b></span>"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed7), label42, 0, 144);
  gtk_widget_set_size_request (label42, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  entryModifierPrenom = gtk_entry_new ();
  gtk_widget_show (entryModifierPrenom);
  gtk_fixed_put (GTK_FIXED (fixed7), entryModifierPrenom, 128, 40);
  gtk_widget_set_size_request (entryModifierPrenom, 176, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryModifierPrenom), 8226);

  buttonConfirmerModif = gtk_button_new ();
  gtk_widget_show (buttonConfirmerModif);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonConfirmerModif, 192, 232);
  gtk_widget_set_size_request (buttonConfirmerModif, 104, 32);
  gtk_container_set_border_width (GTK_CONTAINER (buttonConfirmerModif), 1);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (buttonConfirmerModif), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image29 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox25), image29, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox25), label35, FALSE, FALSE, 0);

  checkbuttonModifierMale = gtk_check_button_new_with_mnemonic (_("Homme"));
  gtk_widget_show (checkbuttonModifierMale);
  gtk_fixed_put (GTK_FIXED (fixed7), checkbuttonModifierMale, 128, 120);
  gtk_widget_set_size_request (checkbuttonModifierMale, 118, 24);

  checkbuttonModifierFemelle = gtk_check_button_new_with_mnemonic (_("Femme"));
  gtk_widget_show (checkbuttonModifierFemelle);
  gtk_fixed_put (GTK_FIXED (fixed7), checkbuttonModifierFemelle, 216, 120);
  gtk_widget_set_size_request (checkbuttonModifierFemelle, 118, 24);

  label43 = gtk_label_new (_("<span foreground =\"#2020\"><b>GSM\t :</b></span>"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed7), label43, 0, 184);
  gtk_widget_set_size_request (label43, 96, 24);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  g_signal_connect ((gpointer) buttonConfirmerModif, "clicked",
                    G_CALLBACK (on_buttonConfirmerModif_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonModifierMale, "toggled",
                    G_CALLBACK (on_checkbuttonModifierMale_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonModifierFemelle, "toggled",
                    G_CALLBACK (on_checkbuttonModifierFemelle_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ModifierEmploye, ModifierEmploye, "ModifierEmploye");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, entryModifierNom, "entryModifierNom");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, entryModifierCin, "entryModifierCin");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, entryModifierGsm, "entryModifierGsm");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, spinbuttonModifierJour, "spinbuttonModifierJour");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, spinbuttonModifierMois, "spinbuttonModifierMois");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, spinbuttonModifierAnnee, "spinbuttonModifierAnnee");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, image30, "image30");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, label36, "label36");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, label41, "label41");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, label47, "label47");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, label46, "label46");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, label42, "label42");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, entryModifierPrenom, "entryModifierPrenom");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, buttonConfirmerModif, "buttonConfirmerModif");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, image29, "image29");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, label35, "label35");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, checkbuttonModifierMale, "checkbuttonModifierMale");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, checkbuttonModifierFemelle, "checkbuttonModifierFemelle");
  GLADE_HOOKUP_OBJECT (ModifierEmploye, label43, "label43");

  return ModifierEmploye;
}

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed8;
  GtkWidget *label48;
  GtkWidget *dialog_action_area1;
  GtkWidget *okbutton1;

  dialog1 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog1, 310, 200);
  gtk_window_set_title (GTK_WINDOW (dialog1), _("Pop-Up"));
  gtk_window_set_resizable (GTK_WINDOW (dialog1), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog1), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed8, TRUE, TRUE, 0);

  label48 = gtk_label_new (_("<span foreground=\"#f936\" ><b>Employ\303\251 ajout\303\251 avec succ\303\251es !</b></span>"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed8), label48, 40, 40);
  gtk_widget_set_size_request (label48, 224, 104);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog1, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (dialog1, label48, "label48");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog1, okbutton1, "okbutton1");

  return dialog1;
}

GtkWidget*
create_dialog2 (void)
{
  GtkWidget *dialog2;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed9;
  GtkWidget *label49;
  GtkWidget *dialog_action_area2;
  GtkWidget *okbutton2;

  dialog2 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog2, 310, 200);
  gtk_window_set_title (GTK_WINDOW (dialog2), _("Pop-Up"));
  gtk_window_set_resizable (GTK_WINDOW (dialog2), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog2), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog2), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog2)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed9, TRUE, TRUE, 0);

  label49 = gtk_label_new (_("<span foreground=\"#f936\"><b>Employ\303\251 modifi\303\251 avec succ\303\251es !</b></span>"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed9), label49, 32, 56);
  gtk_widget_set_size_request (label49, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  dialog_action_area2 = GTK_DIALOG (dialog2)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog2, "dialog2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog2, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (dialog2, label49, "label49");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog2, okbutton2, "okbutton2");

  return dialog2;
}

GtkWidget*
create_dialog3 (void)
{
  GtkWidget *dialog3;
  GtkWidget *dialog_vbox3;
  GtkWidget *fixed10;
  GtkWidget *label51;
  GtkWidget *dialog_action_area3;
  GtkWidget *okbutton3;

  dialog3 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog3, 310, 200);
  gtk_window_set_title (GTK_WINDOW (dialog3), _("dialog3"));
  gtk_window_set_resizable (GTK_WINDOW (dialog3), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog3), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog3), FALSE);

  dialog_vbox3 = GTK_DIALOG (dialog3)->vbox;
  gtk_widget_show (dialog_vbox3);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), fixed10, TRUE, TRUE, 0);

  label51 = gtk_label_new (_("<span foreground=\"#f936\"><b>Employ\303\251 supprim\303\251 avec succ\303\251es !</b></span>"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed10), label51, 32, 56);
  gtk_widget_set_size_request (label51, 240, 40);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  dialog_action_area3 = GTK_DIALOG (dialog3)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  okbutton3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog3), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog3, "dialog3");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog3, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (dialog3, label51, "label51");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog3, okbutton3, "okbutton3");

  return dialog3;
}

GtkWidget*
create_windowPointage (void)
{
  GtkWidget *windowPointage;
  GtkWidget *notebook1;
  GtkWidget *fixed11;
  GtkObject *spinbuttonJourPoint_adj;
  GtkWidget *spinbuttonJourPoint;
  GtkObject *spinbuttonMoisPoint_adj;
  GtkWidget *spinbuttonMoisPoint;
  GtkObject *spinbuttonAnneePoint_adj;
  GtkWidget *spinbuttonAnneePoint;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label57;
  GtkWidget *comboboxentryEtat;
  GtkWidget *buttonCofirmerPointage;
  GtkWidget *label56;
  GtkWidget *comboboxentryID;
  GtkWidget *ongletPointage;
  GtkWidget *fixed12;
  GtkWidget *label62;
  GtkWidget *comboboxentryIDTaux;
  GtkWidget *buttonConsulter;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image33;
  GtkWidget *label63;
  GtkWidget *labelTaux;
  GtkWidget *buttonChercherTaux;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview3;
  GtkWidget *label55;
  GtkWidget *fixed13;
  GtkWidget *label61;

  windowPointage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowPointage, 586, 361);
  gtk_window_set_title (GTK_WINDOW (windowPointage), _("Pointage"));
  gtk_window_set_resizable (GTK_WINDOW (windowPointage), FALSE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (windowPointage), notebook1);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed11);

  spinbuttonJourPoint_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonJourPoint = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJourPoint_adj), 1, 0);
  gtk_widget_show (spinbuttonJourPoint);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbuttonJourPoint, 72, 88);
  gtk_widget_set_size_request (spinbuttonJourPoint, 60, 27);

  spinbuttonMoisPoint_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonMoisPoint = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMoisPoint_adj), 1, 0);
  gtk_widget_show (spinbuttonMoisPoint);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbuttonMoisPoint, 200, 88);
  gtk_widget_set_size_request (spinbuttonMoisPoint, 60, 27);

  spinbuttonAnneePoint_adj = gtk_adjustment_new (1, 2020, 3000, 1, 10, 10);
  spinbuttonAnneePoint = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnneePoint_adj), 1, 0);
  gtk_widget_show (spinbuttonAnneePoint);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbuttonAnneePoint, 344, 88);
  gtk_widget_set_size_request (spinbuttonAnneePoint, 60, 27);

  label58 = gtk_label_new (_("Mois : "));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed11), label58, 128, 80);
  gtk_widget_set_size_request (label58, 88, 40);

  label59 = gtk_label_new (_("Jour : "));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed11), label59, 0, 80);
  gtk_widget_set_size_request (label59, 88, 40);

  label60 = gtk_label_new (_("Etat : "));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed11), label60, 0, 144);
  gtk_widget_set_size_request (label60, 88, 48);

  label57 = gtk_label_new (_("Ann\303\251e : "));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed11), label57, 264, 80);
  gtk_widget_set_size_request (label57, 88, 40);

  comboboxentryEtat = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryEtat);
  gtk_fixed_put (GTK_FIXED (fixed11), comboboxentryEtat, 72, 152);
  gtk_widget_set_size_request (comboboxentryEtat, 128, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryEtat), _("Present"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryEtat), _("Absent"));

  buttonCofirmerPointage = gtk_button_new_with_mnemonic (_("Confimer"));
  gtk_widget_show (buttonCofirmerPointage);
  gtk_fixed_put (GTK_FIXED (fixed11), buttonCofirmerPointage, 272, 144);
  gtk_widget_set_size_request (buttonCofirmerPointage, 112, 48);
  gtk_container_set_border_width (GTK_CONTAINER (buttonCofirmerPointage), 3);

  label56 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed11), label56, 0, 24);
  gtk_widget_set_size_request (label56, 120, 32);

  comboboxentryID = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryID);
  gtk_fixed_put (GTK_FIXED (fixed11), comboboxentryID, 112, 24);
  gtk_widget_set_size_request (comboboxentryID, 120, 32);

  ongletPointage = gtk_label_new (_("Pointage"));
  gtk_widget_show (ongletPointage);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), ongletPointage);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed12);

  label62 = gtk_label_new (_("Identifiant : "));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed12), label62, 40, 8);
  gtk_widget_set_size_request (label62, 104, 48);

  comboboxentryIDTaux = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryIDTaux);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxentryIDTaux, 176, 16);
  gtk_widget_set_size_request (comboboxentryIDTaux, 136, 32);

  buttonConsulter = gtk_button_new ();
  gtk_widget_show (buttonConsulter);
  gtk_fixed_put (GTK_FIXED (fixed12), buttonConsulter, 64, 64);
  gtk_widget_set_size_request (buttonConsulter, 120, 40);
  gtk_container_set_border_width (GTK_CONTAINER (buttonConsulter), 3);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (buttonConsulter), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image33 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox28), image33, FALSE, FALSE, 0);

  label63 = gtk_label_new_with_mnemonic (_("Consulter"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox28), label63, FALSE, FALSE, 0);

  labelTaux = gtk_label_new (_("Taux d'absenteisme : "));
  gtk_widget_show (labelTaux);
  gtk_fixed_put (GTK_FIXED (fixed12), labelTaux, 224, 64);
  gtk_widget_set_size_request (labelTaux, 184, 48);

  buttonChercherTaux = gtk_button_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (buttonChercherTaux);
  gtk_fixed_put (GTK_FIXED (fixed12), buttonChercherTaux, 344, 16);
  gtk_widget_set_size_request (buttonChercherTaux, 66, 29);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed12), scrolledwindow2, 8, 136);
  gtk_widget_set_size_request (scrolledwindow2, 480, 160);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview3);

  label55 = gtk_label_new (_("Taux d'absenteisme"));
  gtk_widget_show (label55);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label55);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed13);

  label61 = gtk_label_new (_("Meilleur employ\303\251"));
  gtk_widget_show (label61);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label61);

  g_signal_connect ((gpointer) buttonCofirmerPointage, "clicked",
                    G_CALLBACK (on_buttonCofirmerPointage_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonConsulter, "clicked",
                    G_CALLBACK (on_buttonConsulter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonChercherTaux, "clicked",
                    G_CALLBACK (on_buttonChercherTaux_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowPointage, windowPointage, "windowPointage");
  GLADE_HOOKUP_OBJECT (windowPointage, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (windowPointage, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (windowPointage, spinbuttonJourPoint, "spinbuttonJourPoint");
  GLADE_HOOKUP_OBJECT (windowPointage, spinbuttonMoisPoint, "spinbuttonMoisPoint");
  GLADE_HOOKUP_OBJECT (windowPointage, spinbuttonAnneePoint, "spinbuttonAnneePoint");
  GLADE_HOOKUP_OBJECT (windowPointage, label58, "label58");
  GLADE_HOOKUP_OBJECT (windowPointage, label59, "label59");
  GLADE_HOOKUP_OBJECT (windowPointage, label60, "label60");
  GLADE_HOOKUP_OBJECT (windowPointage, label57, "label57");
  GLADE_HOOKUP_OBJECT (windowPointage, comboboxentryEtat, "comboboxentryEtat");
  GLADE_HOOKUP_OBJECT (windowPointage, buttonCofirmerPointage, "buttonCofirmerPointage");
  GLADE_HOOKUP_OBJECT (windowPointage, label56, "label56");
  GLADE_HOOKUP_OBJECT (windowPointage, comboboxentryID, "comboboxentryID");
  GLADE_HOOKUP_OBJECT (windowPointage, ongletPointage, "ongletPointage");
  GLADE_HOOKUP_OBJECT (windowPointage, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (windowPointage, label62, "label62");
  GLADE_HOOKUP_OBJECT (windowPointage, comboboxentryIDTaux, "comboboxentryIDTaux");
  GLADE_HOOKUP_OBJECT (windowPointage, buttonConsulter, "buttonConsulter");
  GLADE_HOOKUP_OBJECT (windowPointage, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (windowPointage, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (windowPointage, image33, "image33");
  GLADE_HOOKUP_OBJECT (windowPointage, label63, "label63");
  GLADE_HOOKUP_OBJECT (windowPointage, labelTaux, "labelTaux");
  GLADE_HOOKUP_OBJECT (windowPointage, buttonChercherTaux, "buttonChercherTaux");
  GLADE_HOOKUP_OBJECT (windowPointage, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (windowPointage, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (windowPointage, label55, "label55");
  GLADE_HOOKUP_OBJECT (windowPointage, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (windowPointage, label61, "label61");

  return windowPointage;
}

