/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gesteq (void);
GtkWidget* create_ajoutereq (void);
GtkWidget* create_Recheq (void);
GtkWidget* create_supeq (void);
GtkWidget* create_listeq (void);
GtkWidget* create_modificationwindow (void);
GtkWidget* create_dialog1has (void);
GtkWidget* create_tache2 (void);
GtkWidget* create_dialog2has (void);
GtkWidget* create_dialog3has (void);
