/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *gesteq;
  GtkWidget *ajoutereq;
  GtkWidget *Recheq;
  GtkWidget *supeq;
  GtkWidget *listeq;
  GtkWidget *mod;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  gesteq = create_gesteq ();
  gtk_widget_show (gesteq);
  /*ajoutereq = create_ajoutereq ();
  gtk_widget_show (ajoutereq);
  Recheq = create_Recheq ();
  gtk_widget_show (Recheq);
  supeq = create_supeq ();
  gtk_widget_show (supeq);
  listeq = create_listeq ();
  gtk_widget_show (listeq);
mod = create_modificationwindow ();
  gtk_widget_show (mod);*/

  gtk_main ();
  return 0;
}

