/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowGestionEmployes (void)
{
  GtkWidget *windowGestionEmployes;
  GtkWidget *fixed1;
  GtkWidget *image1;
  GtkWidget *button8;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label7;
  GtkWidget *button9;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label6;
  GtkWidget *button10;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label5;
  GtkWidget *button1;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label4;
  GtkWidget *button5;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label1;
  GtkWidget *button6;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label2;
  GtkWidget *button7;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label3;

  windowGestionEmployes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowGestionEmployes, 500, 500);
  gtk_window_set_title (GTK_WINDOW (windowGestionEmployes), _("Gestion des employ\303\251s"));
  gtk_window_set_resizable (GTK_WINDOW (windowGestionEmployes), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowGestionEmployes), fixed1);

  image1 = create_pixmap (windowGestionEmployes, "final.png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 0, 0);
  gtk_widget_set_size_request (image1, 700, 500);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed1), button8, 152, 360);
  gtk_widget_set_size_request (button8, 200, 56);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button8), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_DND);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_(" Liste des employ\303\251s"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox7), label7, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed1), button9, 152, 264);
  gtk_widget_set_size_request (button9, 200, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button9), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_DND);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_(" Suprrimer un employ\303\251"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed1), button10, 152, 176);
  gtk_widget_set_size_request (button10, 200, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button10), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_DND);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_(" Modifier un employ\303\251"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 152, 80);
  gtk_widget_set_size_request (button1, 200, 56);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button1), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_DND);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_(" Ajouter un employ\303\251"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed1), button5, 192, 8);
  gtk_widget_set_size_request (button5, 96, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button5), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed1), button6, 288, 8);
  gtk_widget_set_size_request (button6, 80, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button6), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-media-rewind", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed1), button7, 368, 8);
  gtk_widget_set_size_request (button7, 120, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button7), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionEmployes, windowGestionEmployes, "windowGestionEmployes");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, button8, "button8");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label7, "label7");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, button9, "button9");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image7, "image7");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label6, "label6");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, button10, "button10");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, button1, "button1");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, button5, "button5");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, button6, "button6");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label2, "label2");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, button7, "button7");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowGestionEmployes, label3, "label3");

  gtk_widget_grab_focus (image1);
  return windowGestionEmployes;
}

GtkWidget*
create_windowAjoutEmploye (void)
{
  GtkWidget *windowAjoutEmploye;
  GtkWidget *fixed2;
  GtkWidget *button11;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label8;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label11;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton1;
  GtkWidget *entry3;
  GtkWidget *label13;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label15;
  GtkWidget *label12;
  GtkWidget *label14;
  GtkWidget *label16;
  GtkWidget *entry4;
  GtkWidget *button14;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label17;
  GtkWidget *button13;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label10;
  GtkWidget *button12;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label9;

  windowAjoutEmploye = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowAjoutEmploye, 500, 500);
  gtk_window_set_title (GTK_WINDOW (windowAjoutEmploye), _("window2"));
  gtk_window_set_resizable (GTK_WINDOW (windowAjoutEmploye), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowAjoutEmploye), fixed2);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed2), button11, 192, 8);
  gtk_widget_set_size_request (button11, 96, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button11), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox8), label8, FALSE, FALSE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 112, 88);
  gtk_widget_set_size_request (entry1, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 112, 144);
  gtk_widget_set_size_request (entry2, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label11 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 32, 88);
  gtk_widget_set_size_request (label11, 88, 32);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Femelle"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton2, 240, 208);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Male"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton1, 128, 208);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 112, 304);
  gtk_widget_set_size_request (entry3, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label13 = gtk_label_new (_("Sexe : "));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 32, 200);
  gtk_widget_set_size_request (label13, 88, 40);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 120, 256);
  gtk_widget_set_size_request (spinbutton1, 80, 24);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton2, 208, 256);
  gtk_widget_set_size_request (spinbutton2, 80, 24);

  spinbutton3_adj = gtk_adjustment_new (1, 1900, 2021, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton3, 296, 256);
  gtk_widget_set_size_request (spinbutton3, 88, 24);

  label15 = gtk_label_new (_("N\303\251(e) le : "));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 24, 248);
  gtk_widget_set_size_request (label15, 96, 40);

  label12 = gtk_label_new (_("Prenom : "));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 24, 144);
  gtk_widget_set_size_request (label12, 88, 32);

  label14 = gtk_label_new (_("Username : "));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 16, 304);
  gtk_widget_set_size_request (label14, 96, 32);

  label16 = gtk_label_new (_("GSM :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 32, 360);
  gtk_widget_set_size_request (label16, 96, 32);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 112, 360);
  gtk_widget_set_size_request (entry4, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed2), button14, 176, 416);
  gtk_widget_set_size_request (button14, 136, 48);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button14), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_DND);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox11), label17, FALSE, FALSE, 0);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed2), button13, 368, 8);
  gtk_widget_set_size_request (button13, 120, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button13), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox10), label10, FALSE, FALSE, 0);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed2), button12, 288, 8);
  gtk_widget_set_size_request (button12, 80, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button12), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-media-rewind", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox9), label9, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAjoutEmploye, windowAjoutEmploye, "windowAjoutEmploye");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, button11, "button11");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label8, "label8");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label11, "label11");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label13, "label13");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label15, "label15");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label12, "label12");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label14, "label14");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label16, "label16");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, button14, "button14");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label17, "label17");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, button13, "button13");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, image11, "image11");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label10, "label10");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, button12, "button12");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, image10, "image10");
  GLADE_HOOKUP_OBJECT (windowAjoutEmploye, label9, "label9");

  return windowAjoutEmploye;
}

GtkWidget*
create_windowModifierEmploye (void)
{
  GtkWidget *windowModifierEmploye;
  GtkWidget *fixed3;
  GtkWidget *entry5;
  GtkWidget *label18;
  GtkWidget *button15;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label19;
  GtkWidget *button23;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image21;
  GtkWidget *label29;
  GtkWidget *button24;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image22;
  GtkWidget *label30;
  GtkWidget *button25;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image23;
  GtkWidget *label31;

  windowModifierEmploye = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowModifierEmploye, 400, 200);
  gtk_window_set_title (GTK_WINDOW (windowModifierEmploye), _("Modifier un employ\303\251"));
  gtk_window_set_resizable (GTK_WINDOW (windowModifierEmploye), FALSE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowModifierEmploye), fixed3);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 128, 64);
  gtk_widget_set_size_request (entry5, 240, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label18 = gtk_label_new (_("Username : "));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 0, 56);
  gtk_widget_set_size_request (label18, 144, 48);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed3), button15, 120, 120);
  gtk_widget_set_size_request (button15, 160, 48);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button15), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_DND);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox12), label19, FALSE, FALSE, 0);

  button23 = gtk_button_new ();
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed3), button23, 40, 8);
  gtk_widget_set_size_request (button23, 96, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button23), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image21 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox20), image21, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox20), label29, FALSE, FALSE, 0);

  button24 = gtk_button_new ();
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed3), button24, 136, 8);
  gtk_widget_set_size_request (button24, 80, 32);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button24), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image22 = gtk_image_new_from_stock ("gtk-media-rewind", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox21), image22, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox21), label30, FALSE, FALSE, 0);

  button25 = gtk_button_new ();
  gtk_widget_show (button25);
  gtk_fixed_put (GTK_FIXED (fixed3), button25, 216, 8);
  gtk_widget_set_size_request (button25, 120, 32);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button25), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image23 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox22), image23, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox22), label31, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowModifierEmploye, windowModifierEmploye, "windowModifierEmploye");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, label18, "label18");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, button15, "button15");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, image13, "image13");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, label19, "label19");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, button23, "button23");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, image21, "image21");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, label29, "label29");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, button24, "button24");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, image22, "image22");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, label30, "label30");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, button25, "button25");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, image23, "image23");
  GLADE_HOOKUP_OBJECT (windowModifierEmploye, label31, "label31");

  return windowModifierEmploye;
}

GtkWidget*
create_windowSupprimerEmploye (void)
{
  GtkWidget *windowSupprimerEmploye;
  GtkWidget *fixed4;
  GtkWidget *label20;
  GtkWidget *entry6;
  GtkWidget *button16;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label21;
  GtkWidget *button21;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image19;
  GtkWidget *label27;
  GtkWidget *button20;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image18;
  GtkWidget *label26;
  GtkWidget *button22;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image20;
  GtkWidget *label28;

  windowSupprimerEmploye = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowSupprimerEmploye, 400, 200);
  gtk_window_set_title (GTK_WINDOW (windowSupprimerEmploye), _("Supprimer un employ\303\251"));
  gtk_window_set_resizable (GTK_WINDOW (windowSupprimerEmploye), FALSE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (windowSupprimerEmploye), fixed4);

  label20 = gtk_label_new (_("Username : "));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 0, 56);
  gtk_widget_set_size_request (label20, 144, 48);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 128, 64);
  gtk_widget_set_size_request (entry6, 240, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed4), button16, 120, 120);
  gtk_widget_set_size_request (button16, 160, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button16), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox13), label21, FALSE, FALSE, 0);

  button21 = gtk_button_new ();
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed4), button21, 40, 8);
  gtk_widget_set_size_request (button21, 96, 32);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button21), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image19 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox18), image19, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox18), label27, FALSE, FALSE, 0);

  button20 = gtk_button_new ();
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed4), button20, 136, 8);
  gtk_widget_set_size_request (button20, 80, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button20), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image18 = gtk_image_new_from_stock ("gtk-media-rewind", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox17), image18, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox17), label26, FALSE, FALSE, 0);

  button22 = gtk_button_new ();
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed4), button22, 216, 8);
  gtk_widget_set_size_request (button22, 120, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button22), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image20 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox19), image20, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox19), label28, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowSupprimerEmploye, windowSupprimerEmploye, "windowSupprimerEmploye");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, label20, "label20");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, button16, "button16");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, image14, "image14");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, label21, "label21");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, button21, "button21");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, image19, "image19");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, label27, "label27");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, button20, "button20");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, image18, "image18");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, label26, "label26");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, button22, "button22");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, image20, "image20");
  GLADE_HOOKUP_OBJECT (windowSupprimerEmploye, label28, "label28");

  return windowSupprimerEmploye;
}

GtkWidget*
create_windowListeEmployes (void)
{
  GtkWidget *windowListeEmployes;
  GtkWidget *fixed5;
  GtkWidget *treeview1;
  GtkWidget *entry7;
  GtkWidget *label22;
  GtkWidget *button19;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image17;
  GtkWidget *label25;
  GtkWidget *button18;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image16;
  GtkWidget *label24;
  GtkWidget *button17;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label23;

  windowListeEmployes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowListeEmployes, 500, 500);
  gtk_window_set_title (GTK_WINDOW (windowListeEmployes), _("Consulter la liste des employ\303\251s"));
  gtk_window_set_resizable (GTK_WINDOW (windowListeEmployes), FALSE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (windowListeEmployes), fixed5);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 64, 56);
  gtk_widget_set_size_request (treeview1, 392, 312);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed5), entry7, 144, 400);
  gtk_widget_set_size_request (entry7, 288, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label22 = gtk_label_new (_("Rechercher : "));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 40, 392);
  gtk_widget_set_size_request (label22, 112, 48);

  button19 = gtk_button_new ();
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed5), button19, 288, 8);
  gtk_widget_set_size_request (button19, 80, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button19), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image17 = gtk_image_new_from_stock ("gtk-media-rewind", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox16), image17, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox16), label25, FALSE, FALSE, 0);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed5), button18, 192, 8);
  gtk_widget_set_size_request (button18, 96, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button18), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image16 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox15), image16, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox15), label24, FALSE, FALSE, 0);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed5), button17, 368, 8);
  gtk_widget_set_size_request (button17, 120, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button17), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox14), label23, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowListeEmployes, windowListeEmployes, "windowListeEmployes");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, label22, "label22");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, button19, "button19");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, image17, "image17");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, label25, "label25");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, button18, "button18");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, image16, "image16");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, label24, "label24");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, button17, "button17");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, image15, "image15");
  GLADE_HOOKUP_OBJECT (windowListeEmployes, label23, "label23");

  return windowListeEmployes;
}

