/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowGestionEmployes (void);
GtkWidget* create_windowAjoutEmploye (void);
GtkWidget* create_windowModifierEmploye (void);
GtkWidget* create_windowSupprimerEmploye (void);
GtkWidget* create_windowListeEmployes (void);
